### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by Urheen** [rueberger/division_detection#2]
Hi Rumberger

>As of July 2020, I am no longer at Janelia and there are no plans to introduce support for training to this package. That being said, the training is relatively straightforward and should be easily reproducible by the experienced ML practitioner - I am happy to correspond via email.

#1 And could you please spend some time fixing the code?

Thank you!

**Comment by rueberger** [comment]
Hi Ziyan, 

Going to close this as we are corresponding via email. 

Regarding the container, I'm not sure when/if I'll be able to patch the Dockerfile as one of the crucial dependencies has gone AWOL. The image you should use is `rueberger/division_detection:patched_gpu`, you should be able to run predictions (but not training) with that.
